# Copyright (c) Humanitarian OpenStreetMap Team
#
# This file is part of Field-TM.
#
#     Field-TM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Field-TM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Field-TM.  If not, see <https:#www.gnu.org/licenses/>.
#

[project]
name = "field-tm"
version = "2026.4.3"
description = "Field Tasking Manager - coordinated field mapping."
authors = [
    {name = "HOTOSM", email = "sysadmin@hotosm.org"},
]
requires-python = ">=3.13"
dependencies = [
    "uvicorn==0.41.0",
    "litestar[jinja]==2.21.1",
    "pydantic==2.9.2",
    "pydantic-settings==2.6.0",
    "geojson-pydantic==1.1.2",
    "python-multipart==0.0.30",
    "psycopg[c,pool]==3.3.3",
    "cryptography==46.0.7",
    "pyxform==4.0.0",
    "pyodk==1.2.1",
    "qfieldcloud-sdk==26.14",
    "osm-login-python==2.0.0",
    "pg-nearest-city==2.0.0",
    "raw-data-api-py==0.3.0",
    "geojson-aoi-parser==0.3.5",
    "hotosm-auth[litestar] @ git+https://github.com/hotosm/login.git@a2a1ce2a395c#subdirectory=auth-libs/python",
    "osm-fieldwork",
    "area-splitter",
]
readme = "../../README.md"
license = "AGPL-3.0-only"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "commitizen>=4.9.1",
    "babel>=2.18.0",
]
test = [
    "pytest==8.3.5",
    "pytest-asyncio==0.24.0",
    "httpx==0.28.1",
    "pyinstrument==5.0.3",
    "coverage==7.15.0",
    "coverage-badge==1.1.2",
    "asgi-lifespan==2.1.0",
]
debug = [
    "debugpy==1.8.20",
]
docs = [
    "mkdocs==1.6.1",
    "mkdocs-material==9.5.42",
    "mkdocstrings-python==1.12.2",
    "mkdocs-exclude==1.0.2",
    "python-dotenv==1.0.1",
    "mkdocs-git-revision-date-localized-plugin==1.3.0",
    "mdx-truly-sane-lists==1.3",
]
monitoring = [
    "sentry-sdk[opentelemetry-otlp]==2.53.0",
    #"opentelemetry-sdk==1.37.0",
    #"opentelemetry-api==1.37.0",
    #"opentelemetry-exporter-otlp==1.37.0",
    "opentelemetry-instrumentation-asgi==0.60b1",
    "opentelemetry-instrumentation-logging==0.60b1",
    "opentelemetry-instrumentation-psycopg==0.60b1",
    "opentelemetry-instrumentation-requests==0.60b1",
]

[tool.ruff]
fix = true
line-length = 88
target-version = "py313"
exclude = [
    ".ruff_cache",
    "app/__version__.py",
]
[tool.ruff.lint]
select = ["I", "E", "W", "D", "B", "F", "N", "Q", "C90","B","S","SIM","PLR","C4","PERF"]
ignore = ["N805", "B008"]
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101", "PLR2004", "S105", "S106","C901", "SIM117"]
[tool.ruff.lint.pydocstyle]
convention = "google"
[tool.ruff.lint.mccabe]
max-complexity = 10
[tool.ruff.lint.pylint]
max-args = 8
max-branches = 12
max-returns = 6
max-statements = 50

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
    "tests",
    "package_tests",
]
pythonpath = [
    "package_tests",
]
asyncio_mode="auto"
asyncio_default_fixture_loop_scope="function"

[tool.commitizen]
name = "cz_conventional_commits"
version = "2026.4.3"
version_provider = "uv"
version_files = [
    "pyproject.toml:version",
    "app/__version__.py",
    "../../chart/Chart.yaml:version",
    "../../chart/Chart.yaml:appVersion",
]
changelog_file = "../../CHANGELOG.md"
update_changelog_on_bump = true
ignored_tag_formats = ["osm-fieldwork-$version", "area-splitter-$version"]

[tool.codespell]
skip = "contrib/*.py,*languages_and_countries.py,*CHANGELOG.md,src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/*,src/backend/packages/osm-fieldwork/osm_fieldwork/update_form.py,src/backend/packages/osm-fieldwork/tests/test_data/*,src/backend/packages/osm-fieldwork/osm_fieldwork/xlsforms/*,src/backend/app/static/images/*"
ignore-words-list = "ProjectIn, Indien"
write-changes = true


[[tool.babel.mappings]]
method = "jinja2"
pattern = "app/templates/**.html"
encoding = "utf-8"

[[tool.babel.mappings]]
method = "python"
pattern = "app/**.py"
encoding = "utf-8"

[tool.uv.sources]
osm-fieldwork = { workspace = true }
area-splitter = { workspace = true }
qfieldcloud-sdk = { git = "https://github.com/hotosm/qfieldcloud-sdk-python", rev = "feat/temp-cgi-plus-user-api" }

[tool.uv.workspace]
members = ["packages/*"]
